export const GENERAL = {
  SONGS_REPO: 'songsRepo',
  ALL_PLAYLISTS: 'allPlaylists',
  MISC: 'misc',
  LAST_KNOWN_STATE: 'lastKnownState',
  CURRENT_PLAYLIST: 'currentPlaylist',
  ALL_SONGS: 'allSongs',
  FAVORITES: 'favorites',
  CUSTOM_PLAYLIST_IDENTIFIER: 'isCustomPlaylist',
  SONG_IDS: 'songIds'
}

export const ACTION_TYPES = {
  UPDATE_ALL_SONGS: 'UPDATE_ALL_SONGS',
  UPDATE_ALL_PLAYLISTS: 'UPDATE_ALL_PLAYLISTS'
}

export const HELPER_TYPES = {
  ADD_PLAYLIST: 'ADD_PLAYLIST',
  REMOVE_PLAYLIST: 'REMOVE_PLAYLIST',
  ADD_SONG_TO_REPO: 'ADD_SONG_TO_REPO',
  REMOVE_SONG_FROM_REPO: 'REMOVE_SONG_FROM_REPO',
  ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST',
  REMOVE_FROM_PLAYLIST: 'REMOVE_FROM_PLAYLIST',
  SET_CURRENT_PLAYLIST: 'SET_CURRENT_PLAYLIST'
}
